---
driver:
  name: terraform
  variable_files:
    - testing.tfvars

provisioner:
  name: terraform

platforms:
  - name: ubuntu

transport:
  name: ssh

verifier:
  name: inspec
  format: junit
  output: ./inspec_output.xml
  groups:
    - name: default
      hostnames: public_dns
      username: ubuntu

suites:
  - name: default
